### ISSUE TITLE
Test report of review branch "translation"

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#36] opened 2015-04-08 10:04 UTC
Yesterday, few bugs were detected with the https://github.com/NielsH/RaidCore/tree/review/translation branch.

Few translations mistake or missing have seen, have been pushed with "fixup!" keyword.

But, with this fix, I saw on SystemDaemon:
- The Datachron message to switch in Pillar phase wasn't working. I don't known why. (no timer refresh)
- Also, I start the fight with a reloadui before and without SD targeted (no UnitCreated). And so the addon don't start the fight. And as I'm playing heal, I don't need to target him immediately.

For the second point. I have the felling there is a important problem with the core engine.

**Comment by Immemor** [comment] 2015-04-08 13:13
For the datachron message, I think It's because the chatFilter is disable.

But it's disable since a long time.

**Comment by NielsH** [comment] 2015-04-08 17:17
This was an older issue I resolved at the time with the RegisterEnableZone - via https://github.com/NielsH/RaidCore/blob/review/translation/RaidCore.lua#L874

This works in combination with the https://github.com/NielsH/RaidCore/blob/master/Modules/SystemDaemons.lua#L15 and L14 - so it should activate automatically when you are in the subzone and have that event active. And it should disable automatically after defeating the boss (event no longer active). I think that's the direction we should search.

Also sorry I can't do much during the week, only weekends I have time or evenings when we cleared DS!

**Comment by Immemor** [comment] 2015-04-08 23:34
Ok ok.

**Comment by Immemor** [comment] 2015-04-09 22:04
Hum, On Warmonger Chuna, timers are wrongs.
The Elemental Pair Hydro and Aileron, well nothing. only print message like "Combat started".

**Comment by NielsH** [comment] 2015-04-11 08:18
I did GA yesterday, and saw the following issues:
- Modules were loaded, but fights were never started. I tested a quick fix, which worked, and that'll confirm that this was also the issue for other fights:  
  Uncomment: https://github.com/NielsH/RaidCore/blob/4c1d29a2a3fca371f7932110d48b9db11b759acb/RaidCore.lua#L855  
  Comment: https://github.com/NielsH/RaidCore/blob/4c1d29a2a3fca371f7932110d48b9db11b759acb/RaidCore.lua#L867  
  Comment:   https://github.com/NielsH/RaidCore/blob/4c1d29a2a3fca371f7932110d48b9db11b759acb/RaidCore.lua#L1552
- Also I noticed that on Ohmna, it only displayed the first pillar, and there were no timers for all the other pillars. However I wasn't able to debug this since we one-shot the boss.

**Comment by NielsH** [comment] 2015-04-11 08:20
On second read... this looks like the ChatMessage event that's there as well might be the cause of the other issues with Chat stuff not triggering? Though it should be listening to that event as self:Start() is ran

**Comment by Immemor** [comment] 2015-04-11 10:40
hum, I will propose you an another code, an another organization. More I'm looking, more I think there no enough tool to debug, to much lines duplicated, too much code written to describe something.

I will take at least 1 week for that, I think so.

**Comment by NielsH** [comment] 2015-04-20 10:47
An issue I was having this week which prevented like.. well, every boss module from running properly :p has been fixed now, see: https://github.com/NielsH/RaidCore/commit/0d021f08a75c6e1aa71d6ef648ab62cd5030b445

So settings can actually load now, heh :)

**Comment by NielsH** [comment] 2015-04-21 18:47
For the datachron message, I saw the issue on system daemons, but I wasn't able to debug a lot there before we killed it.

On Lattice now and I can see the event handler being fired properly, and it is picked up as well properly in the OnChatDC function within the module itself. So it seems the issue is only present in some bosses, but not all.

**Comment by Immemor** [comment] 2015-04-21 18:48
well, with my branch. That work ^^

**Comment by Immemor** [comment] 2015-04-21 18:49
But this week, I will play less since we have some applies to integrate in the team.

**Comment by NielsH** [comment] 2015-04-21 19:26
So with your branch OnChatDC is fixed? Then I don't need to debug that issue :p

**Comment by Immemor** [comment] 2015-04-21 19:28
^^, I changed a lot of thing too. That must be validate too.

I will close the exporting log to clipboard feature so. If you want to integrate it.

**Comment by Immemor** [comment] 2015-04-21 21:07
finally I played tonight. So for datachron, I confirm, that work with my current branch.

I finish first version of log after the raid with some mob, and I push in review.

**Closed as completed** 2015-04-28 14:41 UTC
Labels: bug
